#!/usr/bin/env bash
if [ $BASH_VERSINFO -lt 4 ]; then
    echo [+] please use a bash version 4 or greater
    exit 1
fi
declare -A C
echo '{ "aliasToKeys": ['
a=''
grep ^group ~/.gnupg/gpg.conf | grep -v '<' | while read g; do
    n=$(echo $g|cut -d= -f1|cut -d' ' -f2)
    m=$(echo $g|cut -d= -f2)
    echo $a'{ "alias": "'$n'", "rules": { "info": "email rule", "keys": ['
    a=','
    b=''
    for k in $(echo $m); do
        if [ ${C[$k]+_} ]; then
            r=${C[$k]}
        else
            r=$(gpg-key-resolve $k)
            C[$k]=$r            
        fi
        echo $b'"'$r'"'
        b=','
    done
    echo '], "ignoreFailures": false } }' 
done
echo '] }'
