#!/usr/bin/env bash
resolved_key=''
gpg_key_resolve() {
    resolved_key=$(gpg --with-colon -k "$1"|grep -v rvk|grep -A1 pub|grep fpr|cut -d: -f10|tail -1|sed -e 's/ //g')
}
if [ ${BASH_VERSINFO[0]} -ge 4 ]; then
    declare -A C
fi
cf=${1:-~/.gnupg/gpg.conf}
echo '{ "description": "Thunderbird OpenPGP Alias Rules ('$(date)'; '$(basename "$cf")': '$(openssl dgst -sha256 -r "$cf"|cut -d' ' -f1)')", "rules": ['
a=''
grep ^group "$cf"|grep -v '<'|while read g; do
    n=$(echo $g|cut -d= -f1|cut -d' ' -f2)
    m=$(echo $g|cut -d= -f2)
    echo $a'{ "email": "'$n'", "keys": ['
    a=','
    b=''
    for k in $(echo $m); do
        if [ ${BASH_VERSINFO[0]} -ge 4 ]; then
            if [ ${C[$k]+_} ]; then
                r=${C[$k]}
            else
                gpg_key_resolve "$k"
                r=$resolved_key
                C[$k]=$r
            fi
        else
            gpg_key_resolve "$k"
            r=$resolved_key
        fi
        echo $b'{ "description": "'$k'", "fingerprint": "'$r'" }'
        b=','
    done
    echo '] }' 
done
echo '] }'
