#!/usr/bin/env bash
if [ ${BASH_VERSINFO[0]} -ge 4 ]; then
    declare -A C
fi
echo '{ "description": "Thunderbird OpenPGP Alias Rules", "rules": ['
a=''
grep ^group ${1:-~/.gnupg/gpg.conf} | grep -v '<' | while read g; do
    n=$(echo $g|cut -d= -f1|cut -d' ' -f2)
    m=$(echo $g|cut -d= -f2)
    echo $a'{ "email": "'$n'", "keys": ['
    a=','
    b=''
    for k in $(echo $m); do
        if [ ${BASH_VERSINFO[0]} -ge 4 ]; then
            if [ ${C[$k]+_} ]; then
                r=${C[$k]}
            else
                r=$(gpg-key-resolve $k)
                C[$k]=$r            
            fi
        else
            r=$(gpg-key-resolve $k)
        fi
        echo $b'{ "description": "'$k'", "fingerprint": "'$r'" }'
        b=','
    done
    echo '] }' 
done
echo '] }'
